default_platform(:android)

platform :android do
  desc 'Installs Flutter dependencies'
  private_lane :fetch_dependencies do
    sh('flutter pub get --suppress-analytics')
  end

  desc 'Cleanup Workspace'
  private_lane :clean do
    clean_build_artifacts
  end

  desc 'Setup Keystore'
  private_lane :setup_keystore do
    setup_ci if ENV['CI']

    # Convert the base64 encoded keystore file to a file
    sh('echo $ANDROID_KEYSTORE_FILE_BASE64 | base64 --decode > ../keystore.jks')

    # Create a keystore.properties file
    File.write('../keystore.properties', <<~EOF
      keyAlias=#{ENV['ANDROID_SIGNING_KEY_ALIAS']}
      keyPassword=#{ENV['ANDROID_SIGNING_KEY_PASSWORD']}
      storeFile=../keystore.jks
      storePassword=#{ENV['ANDROID_KEYSTORE_PASSWORD']}
    EOF
    )
  end

  desc 'Run Unit Tests'
  lane :test do
    gradle(task: 'test')
  rescue StandardError => e
    # (Optional) Uncomment the following to report the error to your Slack channel
    # slack(
    #   slack_url: ENV['SLACK_URL'],
    #   message: 'Android Unit Test Failure: ' + e.message,
    #   channel: ENV['SLACK_CHANNEL']
    # )
    raise e
  end

  desc 'Deploy to Google Play (Internal)'
  lane :internal do
    clean
    fetch_dependencies
    setup_keystore

    # increment_version_code?

    # Build the app
    sh('flutter build appbundle --release')

    # Upload the app to Google Play
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['ANDROID_SERVICE_ACCOUNT_JSON'],
      package_name: ENV['ANDROID_PACKAGE_NAME'],
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: 'internal'
    )
  end

  desc 'Deploy to Google Play (Production)'
  lane :production do
    clean
    fetch_dependencies
    setup_keystore

    # Build the app
    sh('flutter build appbundle --release')

    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab', # TODO PATH
      json_key_data: ENV['ANDROID_SERVICE_ACCOUNT_JSON'],
      package_name: ENV['ANDROID_PACKAGE_NAME'],
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: 'production'
    )
  end
end
